### ISSUE TITLE
京豆人，怎么不更新了啊

### ISSUE THREAD

**Issue by miwensheng** [67here/jingdou#1]

**Comment by 67here** [comment]
不想做了，jd弹窗很多，很烦人，很无聊，再坚持下去就必须要收费，计划是2元每月，但是依据点赞数，才30赞，就算30人都付费，不够的，估计愿意付费的也是极少的，就直接放弃不做了，我也不知道玩那个能干什么，还不如淘宝直播，肉眼可见的是不费多少精力就能每天五毛六毛。
另外一个是全民运动会的其它实现方式的脚本都被风控了，只有我这个能继续工作，所以我连发帖子引流都不发了，他们那些挂京豆脚本的都互相攻击服务器，盗卖，我还是离远点比较好。
主要的还是每个人的手机不一样，之前光是屏幕中心点击就有一堆人说不能用，AJ自己的问题一大堆，需要花费更多精力做兼容，付出和回报不对等，简单说就是钱少。
本来和群主说删了，他不想删，就变成存档停更的状态了。

**Comment by miwensheng** [comment]
辛苦大佬了~
